# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniDevApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='userImageUrl',
            field=models.FileField(upload_to=b'./bottlepicture/'),
        ),
    ]
